language: php
php:
- 7.3
before_script:
- cp .env.example .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- pwd
- ls -al
script:
- vendor/bin/phpunit
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa


deploy:
  skip_cleanup: true
  provider: script
  script: vendor/bin/dep deploy
  on:
    branch: master